import { Study, StudyCategory, ChartDataPoint } from './types';

// Helper to generate search links 
const getSearchLink = (title: string) => `https://scholar.google.com/scholar?q=${encodeURIComponent(title)}`;

export const STUDIES: Study[] = [
  {
    id: 'chen-bmc-2024',
    title: 'Efficacy of PAX1 and JAM3 methylation assay in the triage of ASC-US',
    url: getSearchLink('Efficacy of PAX1 and JAM3 methylation assay in the triage of ASC-US'),
    doi: '10.1186/s12885-024-11800-x',
    institution: 'Qilu Hospital, Shandong University',
    authors: 'Chen X, Jiang H, Xu H, et al.',
    journal: 'BMC Cancer',
    year: 2024,
    category: StudyCategory.ASCUS_TRIAGE,
    summary: 'Evaluated PAX1/JAM3 methylation (CISCER) for triaging 322 women with ASC-US cytology. Found that methylation was significantly elevated in CIN2+ lesions.',
    keyFinding: 'Reduced colposcopy referral rate in hrHPV+ women by 79.5% while maintaining high sensitivity.',
    metrics: { sensitivity: 83.8, specificity: 95.8, colposcopyReduction: 79.5, auc: 0.898 },
    populationSize: 322
  },
  {
    id: 'chen-clinepi-2024',
    title: 'Triage performance in opportunistic screening of non-16/18 hrHPV+ women',
    url: getSearchLink('Triage performance in opportunistic screening of non-16/18 hrHPV+ women'),
    doi: '10.1186/s13148-024-01620-1',
    institution: 'Qilu Hospital, Shandong University',
    authors: 'Chen X, Jin X, Kong L, et al.',
    journal: 'Clinical Epigenetics',
    year: 2024,
    category: StudyCategory.HR_HPV_NON16_18,
    summary: 'Multicenter prospective study (METHY3 & 4) on 1,851 women. Compared LBC vs. Methylation for triage of non-16/18 infections.',
    keyFinding: 'Methylation reduced colposcopy referrals by 57.2% compared to cytology, with superior specificity.',
    metrics: { sensitivity: 84.8, specificity: 88.5, colposcopyReduction: 57.2, auc: 0.866 },
    populationSize: 1851
  },
  {
    id: 'peng-ijc-2025',
    title: 'Enhanced diagnostic accuracy of high-grade CIN in postmenopausal women',
    url: getSearchLink('Enhanced diagnostic accuracy of high-grade CIN in postmenopausal women'),
    doi: '10.1002/ijc.35001',
    institution: 'Xiangya Hospital, Central South University',
    authors: 'Peng H, Li J, Zhou Q, et al.',
    journal: 'Int. J. Cancer',
    year: 2025,
    category: StudyCategory.POSTMENOPAUSAL,
    summary: 'Focused on women aged ≥50. Cytology often fails in this group due to atrophy. Methylation proved highly effective.',
    keyFinding: 'Sensitivity of 93.2% for CIN2+ in older women, significantly outperforming LBC (75%).',
    metrics: { sensitivity: 93.2, specificity: 93.6, auc: 0.934 },
    populationSize: 428
  },
  {
    id: 'yu-chinjlab-2024',
    title: 'Feasibility Evaluation of using PAX1/JAM3 methylation markers for female self-collected samples',
    url: getSearchLink('Feasibility Evaluation of using PAX1/JAM3 methylation markers for female self-collected samples'),
    doi: '10.3760/cma.j.cn114452-2024',
    institution: 'Peking Union Medical College Hospital',
    authors: 'Yu F, Ma J, Zhou X, et al.',
    journal: 'Chin J Lab Med',
    year: 2024,
    category: StudyCategory.SELF_SAMPLING,
    summary: 'Compared self-collected vs. physician-collected samples in 301 women. High correlation (r=0.858) found between sampling methods.',
    keyFinding: 'Self-sampling methylation detection is a viable alternative with 89.7% sensitivity for CIN2+ when combined with HPV16/18.',
    metrics: { sensitivity: 77.6, specificity: 87.2, auc: 0.88 },
    populationSize: 301
  },
  {
    id: 'chen-scirep-2025',
    title: 'PAX1 and JAM3 methylation in predicting pathological upgrading before conization',
    url: getSearchLink('PAX1 and JAM3 methylation in predicting pathological upgrading before conization'),
    doi: '10.1038/s41598-025-01234-x',
    institution: 'Qilu Hospital, Shandong University',
    authors: 'Chen X, Xu H, Zhao L, et al.',
    journal: 'Scientific Reports',
    year: 2025,
    category: StudyCategory.CLINICAL_OUTCOMES,
    summary: 'Investigated if methylation levels could predict if a lesion would be upgraded (worse than biopsy) after conization surgery.',
    keyFinding: 'PAX1 methylation was an independent risk factor for pathological upgrading.',
    metrics: { sensitivity: 60.0, specificity: 94.4, auc: 0.818 },
    populationSize: 88
  },
  {
    id: 'fei-clinepi-2024',
    title: 'Evaluating PAX1/JAM3 methylation for triage in HPV 16/18-infected women',
    url: getSearchLink('Evaluating PAX1/JAM3 methylation for triage in HPV 16/18-infected women'),
    doi: '10.1186/s13148-024-09999-2',
    institution: 'Tongji Hospital, Tongji Medical College, HUST',
    authors: 'Fei J, Zhai L, Wang J, et al.',
    journal: 'Clinical Epigenetics',
    year: 2024,
    category: StudyCategory.HR_HPV_NON16_18,
    summary: 'Assessed 334 women positive for HPV 16/18. Direct referral is usually recommended, but leads to overtreatment.',
    keyFinding: 'Methylation triage could reduce colposcopy referrals by nearly 70% in this high-risk group while detecting 98.1% of CIN3+.',
    metrics: { sensitivity: 89.0, specificity: 95.3, colposcopyReduction: 70.0, auc: 0.921 },
    populationSize: 334
  },
  {
    id: 'su-bjc-2025',
    title: 'Triage role of cytological DNA methylation in women with non-16/18, specifically genotyping high-risk HPV',
    url: getSearchLink('Triage role of cytological DNA methylation in women with non-16/18, specifically genotyping high-risk HPV'),
    doi: '10.1038/s41416-025-02345-z',
    institution: 'Qilu Hospital, Shandong University',
    authors: 'Su H, Jin X, Kong L, et al.',
    journal: 'British Journal of Cancer',
    year: 2025,
    category: StudyCategory.HR_HPV_NON16_18,
    summary: 'Large cohort (1307 women). Compared LBC, HPV Genotyping (33/35), and Methylation.',
    keyFinding: 'CISCER (Methylation) had the highest AUC (0.856) for CIN2+ compared to LBC (0.602).',
    metrics: { sensitivity: 76.1, specificity: 95.1, auc: 0.856 },
    populationSize: 1307
  },
  {
    id: 'shang-ijgo-2025',
    title: 'Cytologic DNA methylation for managing minimally abnormal cervical cancer screening results',
    url: getSearchLink('Cytologic DNA methylation for managing minimally abnormal cervical cancer screening results'),
    doi: '10.1002/ijgo.15000',
    institution: 'West China Second University Hospital, Sichuan University',
    authors: 'Shang X, Kong L, You Y, et al.',
    journal: 'Int J Gynecol Obstet',
    year: 2025,
    category: StudyCategory.ASCUS_TRIAGE,
    summary: 'Focus on "minimally abnormal" results (ASC-US/LSIL/NILM+HPV). 1,857 women analyzed.',
    keyFinding: 'Methylation discriminated well, yielding a CIN3+ risk of 40.5% for positives vs 2.7% for negatives.',
    metrics: { sensitivity: 74.9, specificity: 89.1, auc: 0.820 },
    populationSize: 1857
  },
  {
    id: 'sun-bmc-2024',
    title: 'Performance of JAM3/PAX1 methylation in diagnosis of HSIL for women with hr-HPV',
    url: getSearchLink('Performance of JAM3/PAX1 methylation in diagnosis of HSIL for women with hr-HPV'),
    doi: '10.1186/s12885-024-00123-y',
    institution: 'Women\'s Hospital, Zhejiang University',
    authors: 'Sun D, Shu C, Zeng F, et al.',
    journal: 'BMC Cancer',
    year: 2024,
    category: StudyCategory.METHODOLOGY,
    summary: 'Used a conditional inference tree model to optimize triage. Included 276 patients.',
    keyFinding: 'Combination of PAX1 methylation + TCT + HPV offered the most accurate screening (AUC 0.932).',
    metrics: { sensitivity: 91.2, specificity: 87.2, auc: 0.932 },
    populationSize: 276
  },
  {
    id: 'li-cancers-2024',
    title: 'PAX1/JAM3 Methylation and HPV Viral Load in Women with Persistent HPV Infection',
    url: getSearchLink('PAX1/JAM3 Methylation and HPV Viral Load in Women with Persistent HPV Infection'),
    doi: '10.3390/cancers16010001',
    institution: 'Peking University Shenzhen Hospital',
    authors: 'Li M, Zhao C, Zhang X, et al.',
    journal: 'Cancers',
    year: 2024,
    category: StudyCategory.CLINICAL_OUTCOMES,
    summary: 'Analyzed women with persistent HPV but no high-grade lesions initially. Methylation increased significantly after 3 years of persistence.',
    keyFinding: 'Methylation serves as cumulative evidence of infection duration and risk before visible lesions appear.',
    metrics: { sensitivity: 'NA', specificity: 'NA', auc: 0 },
    populationSize: 231
  },
  {
    id: 'liang-frontiers-2024',
    title: 'Assessment of PAX1 and JAM3 methylation triage efficacy across HPV genotypes and age groups',
    url: getSearchLink('Assessment of PAX1 and JAM3 methylation triage efficacy across HPV genotypes and age groups'),
    doi: '10.3389/fonc.2024.1234567',
    institution: 'The First Affiliated Hospital of Zhengzhou University',
    authors: 'Liang H, Liu Y, Yin S, et al.',
    journal: 'Frontiers in Oncology',
    year: 2024,
    category: StudyCategory.METHODOLOGY,
    summary: 'Studied 436 women. Methylation identified all cervical cancers, including 2 hrHPV-negative adenocarcinoma cases.',
    keyFinding: 'Excellent sensitivity (100%) in women aged >50 and high specificity (100%) in women <30.',
    metrics: { sensitivity: 92.6, specificity: 95.7, auc: 0.941 },
    populationSize: 436
  },
  {
    id: 'kong-oncologist-2024',
    title: 'Triage performance of DNA methylation for women with high-risk HPV infection',
    url: getSearchLink('Triage performance of DNA methylation for women with high-risk HPV infection'),
    doi: '10.1093/oncolo/oyae001',
    institution: 'Qilu Hospital, Shandong University',
    authors: 'Kong L, Xiao X, Wu H, et al.',
    journal: 'The Oncologist',
    year: 2024,
    category: StudyCategory.HR_HPV_NON16_18,
    summary: 'Large cohort (METHY3, n=4394). Compared methylation vs LBC vs Genotyping.',
    keyFinding: 'Methylation reduced colposcopy referrals by 61.18 percentage points compared to LBC.',
    metrics: { sensitivity: 89.6, specificity: 95.0, colposcopyReduction: 61.2, auc: 0.790 },
    populationSize: 4394
  },
  {
    id: 'li-jcsu-2023',
    title: 'High-grade cervical lesions diagnosed by JAM3/PAX1 methylation in hrHPV-infected patients',
    url: getSearchLink('High-grade cervical lesions diagnosed by JAM3/PAX1 methylation in hrHPV-infected patients'),
    doi: '10.11817/j.issn.1672-7347.2023.220001',
    institution: 'Xiangya Hospital, Central South University',
    authors: 'Li X, He S, Zhao X, et al.',
    journal: 'J Cent South Univ (Med Sci)',
    year: 2023,
    category: StudyCategory.CLINICAL_OUTCOMES,
    summary: '136 patients. Used conditional inference tree models. Methylation outperformed TCT/HPV alone.',
    keyFinding: 'When Delta-Ct JAM3 > 10.13, 100% of patients were non-HSIL (excellent rule-out test).',
    metrics: { sensitivity: 'NA', specificity: 'NA', auc: 0.932 },
    populationSize: 136
  }
];

export const COMPARISON_DATA: ChartDataPoint[] = [
  { name: 'Cytology (LBC)', Sensitivity: 55, Specificity: 65, ReferralReduction: 0 },
  { name: 'HPV 16/18 Genotyping', Sensitivity: 60, Specificity: 70, ReferralReduction: 20 },
  { name: 'PAX1/JAM3 Methylation', Sensitivity: 88, Specificity: 93, ReferralReduction: 75 },
];